# Generated by Django 5.2.4 on 2025-10-25 13:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('short_name', models.CharField(blank=True, help_text="Singkatan, mis. 'LAL', 'BOS'", max_length=10)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(max_length=100)),
                ('full_name', models.CharField(max_length=120)),
                ('jersey_number', models.PositiveIntegerField(blank=True, null=True)),
                ('position', models.CharField(choices=[('PG', 'Point Guard'), ('SG', 'Shooting Guard'), ('SF', 'Small Forward'), ('PF', 'Power Forward'), ('C', 'Center')], default='SG', max_length=2)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['team', 'full_name'],
                'unique_together': {('team', 'full_name')},
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('home_team', models.CharField(max_length=100)),
                ('away_team', models.CharField(max_length=100)),
                ('tipoff_at', models.DateTimeField(db_index=True, help_text='Waktu mulai pertandingan (tip-off)')),
                ('venue', models.CharField(blank=True, db_index=True, max_length=120)),
                ('image_url', models.URLField(blank=True, help_text='URL gambar pertandingan dari Google')),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('live', 'Live'), ('finished', 'Finished'), ('canceled', 'Canceled')], db_index=True, default='scheduled', max_length=10)),
                ('home_score', models.PositiveSmallIntegerField(default=0)),
                ('away_score', models.PositiveSmallIntegerField(default=0)),
                ('q1_home', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('q1_away', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('q2_home', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('q2_away', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('q3_home', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('q3_away', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('q4_home', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('q4_away', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('ot1_home', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('ot1_away', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('ot2_home', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('ot2_away', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('ot3_home', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('ot3_away', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('season', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='matches.season')),
            ],
            options={
                'ordering': ['-tipoff_at'],
            },
        ),
        migrations.CreateModel(
            name='PlayerBoxScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(max_length=100)),
                ('is_starter', models.BooleanField(default=False)),
                ('minutes', models.DecimalField(decimal_places=2, default=0.0, help_text='Menit bermain (desimal, mis. 32.5 untuk 32:30)', max_digits=4)),
                ('pts', models.PositiveSmallIntegerField(default=0)),
                ('reb', models.PositiveSmallIntegerField(default=0)),
                ('ast', models.PositiveSmallIntegerField(default=0)),
                ('stl', models.PositiveSmallIntegerField(default=0)),
                ('blk', models.PositiveSmallIntegerField(default=0)),
                ('tov', models.PositiveSmallIntegerField(default=0)),
                ('pf', models.PositiveSmallIntegerField(default=0)),
                ('fg_made', models.PositiveSmallIntegerField(default=0)),
                ('fg_att', models.PositiveSmallIntegerField(default=0)),
                ('tp_made', models.PositiveSmallIntegerField(default=0)),
                ('tp_att', models.PositiveSmallIntegerField(default=0)),
                ('ft_made', models.PositiveSmallIntegerField(default=0)),
                ('ft_att', models.PositiveSmallIntegerField(default=0)),
                ('plus_minus', models.SmallIntegerField(default=0)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='box_scores', to='matches.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='box_scores', to='matches.player')),
            ],
            options={
                'ordering': ['-is_starter', '-minutes', 'player__full_name'],
                'indexes': [models.Index(fields=['match', 'team'], name='matches_pla_match_i_1ec2c2_idx'), models.Index(fields=['player'], name='matches_pla_player__337cfa_idx')],
                'unique_together': {('match', 'player')},
            },
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['home_team', 'away_team'], name='matches_mat_home_te_1982d0_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['status', 'tipoff_at'], name='matches_mat_status_e2f95a_idx'),
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.CheckConstraint(condition=models.Q(('home_team', models.F('away_team')), _negated=True), name='match_home_neq_away'),
        ),
    ]
