# Generated by Django 5.2.7 on 2025-10-23 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playerboxscore',
            options={'ordering': ['-is_starter', '-minutes', 'player__full_name']},
        ),
        migrations.AlterField(
            model_name='playerboxscore',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='box_scores', to='matches.match'),
        ),
        migrations.AlterField(
            model_name='playerboxscore',
            name='minutes',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Menit bermain (desimal, mis. 32.5 untuk 32:30)', max_digits=4),
        ),
        migrations.AlterField(
            model_name='playerboxscore',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='box_scores', to='matches.player'),
        ),
        migrations.AlterField(
            model_name='playerboxscore',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='box_scores', to='matches.team'),
        ),
        migrations.AlterField(
            model_name='playerboxscore',
            name='tp_att',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playerboxscore',
            name='tp_made',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
