# Generated by Django 5.2.7 on 2025-10-23 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_alter_playerboxscore_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='height_cm',
        ),
        migrations.RemoveField(
            model_name='player',
            name='weight_kg',
        ),
        migrations.AddField(
            model_name='match',
            name='image',
            field=models.ImageField(blank=True, help_text='Gambar pertandingan', null=True, upload_to='matches/'),
        ),
    ]
