# Generated by Django 5.2.7 on 2025-10-23 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_remove_player_height_cm_remove_player_weight_kg_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='image',
        ),
        migrations.AddField(
            model_name='match',
            name='image_url',
            field=models.URLField(blank=True, help_text='URL gambar pertandingan dari Google'),
        ),
    ]
