# Generated by Django 5.2.7 on 2025-10-23 17:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0004_remove_match_image_match_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='uuid',
            field=models.UUIDField(db_index=True, editable=False, unique=True, null=True),
        ),
        migrations.RunSQL(
            "UPDATE matches_match SET uuid = lower(hex(randomblob(4)) || '-' || hex(randomblob(2)) || '-4' || substr(hex(randomblob(2)), 2) || '-' || substr('89ab', abs(random()) % 4 + 1, 1) || substr(hex(randomblob(2)), 2) || '-' || hex(randomblob(6)))",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name='match',
            name='uuid',
            field=models.UUIDField(db_index=True, editable=False, unique=True),
        ),
    ]
