# Generated by Django 5.2.7 on 2025-10-24 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0005_auto_20251024_0005'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['team', 'full_name']},
        ),
        migrations.RenameIndex(
            model_name='match',
            new_name='matches_mat_home_te_1982d0_idx',
            old_name='matches_mat_home_te_a56e02_idx',
        ),
        migrations.RenameIndex(
            model_name='playerboxscore',
            new_name='matches_pla_match_i_1ec2c2_idx',
            old_name='matches_pla_match_i_41a1be_idx',
        ),
        migrations.AlterField(
            model_name='match',
            name='away_team',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='match',
            name='home_team',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='playerboxscore',
            name='team',
            field=models.CharField(max_length=100),
        ),
    ]
