# Generated by Django 5.2.7 on 2025-10-24 04:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0006_alter_player_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
