# Generated by Django 5.2.4 on 2025-10-25 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('logo', models.URLField(blank=True, null=True)),
                ('region', models.CharField(choices=[('us', 'United States'), ('eu', 'Europe'), ('as', 'Asia'), ('af', 'Africa'), ('sa', 'South America'), ('oc', 'Oceania')], default='us', max_length=2)),
                ('founded', models.DateField()),
                ('description', models.TextField()),
            ],
        ),
    ]
