# Generated by Django 5.2.7 on 2025-10-14 07:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[], max_length=50)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('is_featured', models.BooleanField(default=False)),
            ],
        ),
    ]
