# Generated by Django 5.2.4 on 2025-10-21 18:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('nba', 'NBA'), ('ibl', 'IBL'), ('fiba', 'FIBA'), ('transfer', 'Transfers & Trades'), ('highlight', 'Game Highlights'), ('analysis', 'Team & Player Analysis')], max_length=50)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
