# Generated by Django 5.2.7 on 2025-10-14 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='is_featured',
        ),
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.CharField(choices=[('nba', 'NBA'), ('ibl', 'IBL'), ('fiba', 'FIBA'), ('transfer', 'Transfers & Trades'), ('highlight', 'Game Highlights'), ('analysis', 'Team & Player Analysis')], max_length=50),
        ),
    ]
