# Generated by Django 5.2.7 on 2025-10-24 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=10)),
                ('team', models.CharField(max_length=50)),
                ('points_per_game', models.FloatField()),
                ('assists_per_game', models.FloatField()),
                ('rebounds_per_game', models.FloatField()),
            ],
        ),
    ]
